#cloud-config
runcmd:
  - echo 1 | tee /proc/sys/net/ipv4/ip_forward
  - sed -i '/net.ipv4.ip_forward=1/s/^#//g' /etc/sysctl.conf
  - sed -i '/net.ipv4.conf.all.accept_redirects=0/s/^#//g' /etc/sysctl.conf
  - sed -i '/net.ipv4.conf.all.send_redirects=0/s/^#//g' /etc/sysctl.conf
  - sysctl -p
  - mkdir /etc/iptables
  - iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
  - iptables-save > /etc/iptables/rules.v4
